provides = "go"
version = "1.15.7"
checksum = "c8686a66e7786955e2a8eb6d95630bb6369eaacfb269b438e0ccd3a5f188d8d9"
tarball = "https://golang.org/dl/go1.15.7.linux-amd64.tar.gz"
licence = "bsd-style"

[commands]
workingDir = "go"
configure = "echo skip"
compile = "echo skip"
install = "sh {{ .ManifestDir }}/install.sh"

[profiles]
[profiles.default]
deps = []
