provides = "vinit"
version = "0.6.0"
checksum = "c9d46174e543c1854728a7accdb0d213b2607beac630a4a2522a51aebae8c547"
tarball = "https://github.com/vinyl-linux/vinit/releases/download/0.6.0/vinit-x86_64.tar.bz2"
licence = "bsd-3"

[commands]
workingDir = "vinit-x86_64"
configure = "echo skip"
compile = "make certs/server-cert.pem"
install = "sh {{ .ManifestDir }}/install.sh"

[profiles]
[profiles.default]
deps = []
