provides = "autoconf"
version = "2.71"
checksum = "1e9ac41b8ea0cb8a287307ae9083f2e1f1a337ead46eff709e01f533d78d9eca"
tarball = "https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.gz"
licence = "gpl"

[commands]
workingDir = "autoconf-2.71"

[profiles]
[profiles.default]
deps = []
