provides = "vin"
version = "0.12.0"
checksum = "9ff748251f2d14b65c6b6158f4b4ca9cc66a2ad6b20c58de7b3cc76c8e104211"
tarball = "https://github.com/vinyl-linux/vin/releases/download/0.12.0/vin-linux-x86_64.tar.bz2"
licence = "bsd-3"
service_directory = "99-vind"

[commands]
workingDir = "vin-linux-x86_64"
configure = "echo skipping configure"
compile = "./vin advise"
install = "sh {{ .ManifestDir }}/install.sh"

[profiles]
[profiles.default]
