provides = "vinyl-sdk"
version = "1.0.0"
meta = true
licence = "bsd-3"

[profiles]
[profiles.default]
deps = [
     ["gcc", "10.2.0"],
     ["gmp", "6.2.1"],
     ["go", "1.15.8"],
     ["m4", "1.4.18"],
     ["mfpr", "4.1.0"],
     ["mpc", "1.2.1"],
     ["openssl", "1.1.1"],
     ["perl", "5.32.1"],
]
