provides = "openssl"
version = "1.1.1"
checksum = "f25d746d72dd0fa0d15aaf46d1ceda894a13aa8a267cb671ae8fe88f264aa772"
tarball = "https://github.com/openssl/openssl/archive/OpenSSL_1_1_1i.tar.gz"
licence = "apache-2.0"

[commands]
workingDir = "openssl-OpenSSL_1_1_1i"
configure = "./Configure linux-x86_64 --prefix=/usr --libdir=/lib --openssldir=/etc/ssl no-shared no-zlib no-async no-comp no-idea no-mdc2 no-rc5 no-ec2m no-sm2 no-sm4 no-ssl2 no-ssl3 no-seed no-weak-ssl-ciphers enable-ec_nistp_64_gcc_128 -Wa,--noexecstack"

[profiles]
[profiles.default]
deps = [
     ["perl", ">= 5.32.1"],
]
