provides = "vinit"
version = "0.4.0"
checksum = "6f05287f33bbc0a47278b26fd150762fff722b2464d990c67137aa820d35f0f4"
tarball = "https://github.com/vinyl-linux/vinit/releases/download/0.4.0/vinit-x86_64.tar.bz2"
licence = "bsd-3"

[commands]
workingDir = "vinit-x86_64"
configure = "echo skip"
compile = "make certs/server-cert.pem"
install = "sh {{ .ManifestDir }}/install.sh"

[profiles]
[profiles.default]
deps = []
