provides = "vinyl"
version = "0.1.0"
meta = true

[profiles]
[profiles.default]
deps = [
     ["vinit", "=0.8.0-rc1"],
     ["vin", "=0.12.1"],
     ["linux-utils", "=0.1.1"],
     ["vc", "=0.3.2"],
]
