provides = "vinit"
version = "0.1.1"
checksum = "1f854108b2ddb0c4d42e280849d7f828f04a6a59f468a7b6c48ae48001e2cbf2"
tarball = "https://github.com/vinyl-linux/vinit/releases/download/0.1.1/vinit-x86_64.tar.bz2"
licence = "bsd-3"

[commands]
workingDir = "vinit-x86_64"
configure = "echo skip"
compile = "make certs/server-cert.pem"
install = "sh {{ .ManifestDir }}/install.sh"

[profiles]
[profiles.default]
deps = []
