provides = "vin"
version = "0.5.1"
checksum = "ea7b4db446d8fed1ac58bbe0cfc2ba4e886d6013dfd4e665b18a675caa1b34f6"
tarball = "https://github.com/vinyl-linux/vin/archive/0.5.1.tar.gz"
licence = "bsd-3"

[commands]
workingDir = "vin-0.5.1"
configure = "echo skip"

[profiles]
[profiles.default]
deps = [
     ["go", ">=1.15.0"],
]
